all: clean Nat1.class Nat2.class

Nat1.class: Nat1.java
	javac Nat1.java
	java Nat1

Nat2.class: Nat2.java
	javac Nat2.java
	java Nat2

Nat3.class: Nat3.java
	javac Nat3.java
	java Nat3

.PHONY: clean
clean:
	rm -f *.class


